version: '2'
services:
  thresher_api:
    # python:2.7-slim installs postgres 9.4 client
    image: goodly/textthresher:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
      - django_rq
    environment:
      DATABASE_URL: 'postgres://zz:testonly3UkM429Yp@db:5432/thresher'
      SECRET_KEY: 'testonlyZTnB25g,jyH7N9:EiAH5shE8K20B93Q9qtOgwgX!FSo1FwGS-zv;MX;C'

  import_export_worker:
    # Same image as thresher_api
    # Runs the queue for importing articles and schemas and exporting projects and tasks
    image: goodly/textthresher:latest
    depends_on:
      - django_rq
    environment:
      DATABASE_URL: 'postgres://zz:testonly3UkM429Yp@db:5432/thresher'
    command: ["python", "/home/thresher/data/rqworker.py"]

  nlp_hints:
    image: goodly/nlp_hints:latest
    depends_on:
      - django_rq

  django_rq:
    image: redis:3.2.9

  pybossa:
    # ubuntu:14.04 installs postgres 9.4 client
    image: goodly/pybossa:latest
    environment:
      - PYBOSSA_SECRET=test-only-y8y2i4ISpfwEMhLjUfXH9e5qA8qJkKA31tuLakvy
      - PYBOSSA_SESSION_SECRET=test-only-y8y2i4ISpfwEMhLjUfXH9e5qA8qJkKA31tuLakvy
      - PYBOSSA_DATABASE_URL=postgresql://pybossa:tester@db/pybossa
      - PYBOSSA_ITSDANGEROUS_SECRET=test-only-2R1ucOk8KxEeh5SCaXcWPt4oDf2sHQvpiyHAPoyX
      - PYBOSSA_BRAND=Pybossa
      - PYBOSSA_TITLE=Pybossa
      - PYBOSSA_LOGO=default_logo.svg
    depends_on:
      - db
    ports:
      - "3002:80"

  db:
    # postgres:9.4
    image: goodly/textthresher_db:latest
    environment:
      - POSTGRES_USER=zz
      - POSTGRES_PASSWORD=testonly3UkM429Yp
      - POSTGRES_DB=thresher
